name: 'STARR & CO'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.03185052168555558
title: 'STARR & CO'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d7cab7'
    - '#afa697'
    - '#2e2d28'
    - '#524b41'
  brandStrength: 0.11774796899408102
  lightness: 0.4137374081183225
  saturation: 0.06276972242631018
  rhythmicContrast: 0.9178770440630615
purpose: []
